// Rebuilds the embedded WebAssembly (rust/par-wasm -> src/wasm/wasmBytes.ts) or checks that it is current.
//   node tools/xpar/wasm-build.mjs          cargo build --release --target wasm32-unknown-unknown, then regenerate wasmBytes.ts
//   node tools/xpar/wasm-build.mjs --check  no Rust needed: the committed binary must match the hash of the Rust sources
import { spawnSync } from 'node:child_process';
import { createHash } from 'node:crypto';
import { readdirSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = resolve(dirname(fileURLToPath(import.meta.url)), '../..');
const crate = resolve(root, 'rust/par-wasm');
const out = resolve(root, 'src/wasm/wasmBytes.ts');
const sha = (b) => createHash('sha256').update(b).digest('hex');

/** Hash of everything that decides the binary: manifest, lockfile, cargo config and every source file. */
export const sourceHash = () => {
  const files = ['Cargo.toml', 'Cargo.lock', '.cargo/config.toml', ...readdirSync(resolve(crate, 'src')).sort().map((f) => `src/${f}`)];
  const h = createHash('sha256');
  for (const f of files) h.update(`${f}\0`).update(readFileSync(resolve(crate, f))).update('\0');
  return h.digest('hex');
};

const recorded = () => {
  const t = readFileSync(out, 'utf8');
  const get = (k) => new RegExp(`${k} = '([0-9a-f]+|[A-Za-z0-9+/=]+)'`).exec(t)?.[1];
  return { src: get('WASM_SRC_HASH'), bin: get('WASM_SHA256'), b64: get('WASM_B64') };
};

if (process.argv.includes('--check')) {
  const r = recorded();
  const bad = [];
  if (r.src !== sourceHash()) bad.push('Rust sources changed since the committed binary was built: run `npm run build:wasm`');
  if (!r.b64 || sha(Buffer.from(r.b64, 'base64')) !== r.bin) bad.push('embedded binary does not match its recorded hash');
  if (bad.length) {
    console.error(bad.join('\n'));
    process.exit(1);
  }
  console.log(`wasm ok: sources ${r.src.slice(0, 12)}, binary ${r.bin.slice(0, 12)}`);
} else {
  const b = spawnSync('cargo', ['build', '--release', '--target', 'wasm32-unknown-unknown', '--locked'], { cwd: crate, stdio: 'inherit' });
  if (b.status !== 0) {
    console.error('cargo build failed (is the target installed? `rustup target add wasm32-unknown-unknown`)');
    process.exit(1);
  }
  const bin = readFileSync(resolve(crate, 'target/wasm32-unknown-unknown/release/par_wasm.wasm'));
  writeFileSync(out, `// GENERATED by tools/xpar/wasm-build.mjs from rust/par-wasm. Do not edit; run \`npm run build:wasm\`.\nexport const WASM_SRC_HASH = '${sourceHash()}';\nexport const WASM_SHA256 = '${sha(bin)}';\nexport const WASM_B64 = '${bin.toString('base64')}';\n`);
  console.log(`wasm: ${bin.length} bytes -> ${out}`);
}
