import type { Lang } from './i18n';

/** What to look for in each preset: [en, tr, ru]. */
const H: Record<string, [string, string, string]> = {
  basic: ['Outline and shadow around white text, an italic serif line at the top, then bold / italic / underline / strike runs.', 'Beyaz metinde kenar ve gölge, üstte italik serif satır, ardından kalın / italik / altı çizili / üstü çizili parçalar.', 'Контур и тень у белого текста, курсивная строка с засечками сверху, ниже жирный, курсив, подчёркивание и зачёркивание.'],
  pos: ['Each label sits exactly at the coordinates it names. The last line must use the first \\pos.', 'Her etiket adındaki koordinatta durmalı. Son satır ilk \\pos değerini kullanmalı.', 'Каждая надпись стоит ровно в названных координатах. Последняя строка должна использовать первый \\pos.'],
  move: ['Three lines slide linearly; the second waits 1.5 s and arrives at 4.5 s.', 'Üç satır doğrusal kayar; ikincisi 1,5 sn bekler ve 4,5 sn\'de varır.', 'Три строки движутся линейно; вторая ждёт 1,5 с и приходит на 4,5 с.'],
  an: ['Nine labels, each in the cell its number says (7 8 9 on top, 1 2 3 at the bottom).', 'Dokuz etiket, numarasının gösterdiği hücrede (üstte 7 8 9, altta 1 2 3).', 'Девять надписей, каждая в своей ячейке (сверху 7 8 9, снизу 1 2 3).'],
  fad: ['Fade in and out, the 7-argument \\fade holds in the middle, the last one only fades out.', 'Solarak girer ve çıkar; 7 argümanlı \\fade ortada sabit kalır, sonuncu yalnız solarak çıkar.', 'Появление и исчезновение; семиаргументный \\fade держится в середине, последняя строка только гаснет.'],
  t: ['Scale growth, accelerated rotation, stacked colour changes, a whole-line \\t and a hard step at 3 s.', 'Büyüme, ivmeli dönüş, art arda renk değişimleri, süresiz \\t ve 3. saniyede ani geçiş.', 'Рост масштаба, вращение с ускорением, цепочка смен цвета, \\t без времени и резкий скачок на 3 с.'],
  rot: ['frx flips around the horizontal axis, fry around the vertical one, frz spins; the \\org line orbits a point below it.', 'frx yatay, fry dikey eksende döner, frz düzlemde döner; \\org satırı altındaki noktanın etrafında dolanır.', 'frx вращает вокруг горизонтальной оси, fry вокруг вертикальной, frz в плоскости; строка с \\org обращается вокруг точки ниже.'],
  shear: ['fax slants horizontally, fay vertically. Known: headless Chromium on Linux draws positive fax without slant (rasterizer issue).', 'fax yatay, fay dikey eğer. Bilinen: Linux\'ta headless Chromium pozitif fax\'ı eğimsiz çiziyor (rasterizer sorunu).', 'fax наклоняет по горизонтали, fay по вертикали. Известно: headless Chromium на Linux рисует положительный fax без наклона (проблема растеризатора).'],
  scale: ['Narrow / wide and short / tall text; relative \\fs+ and \\fs- change size mid-line.', 'Dar / geniş ve kısa / uzun metin; göreli \\fs+ ve \\fs- satır ortasında boyutu değiştirir.', 'Узкий / широкий и низкий / высокий текст; относительные \\fs+ и \\fs- меняют размер посреди строки.'],
  fsp: ['Letter spacing: normal, wide, tight, and growing over time.', 'Harf aralığı: normal, geniş, dar ve zamanla artan.', 'Межбуквенный интервал: обычный, широкий, узкий и растущий со временем.'],
  color: ['Primary, outline and shadow colours, alpha on fill and outline, and an animated colour and alpha fade.', 'Dolgu, kenar ve gölge renkleri, dolgu ve kenarda alfa, animasyonlu renk ve alfa geçişi.', 'Цвета заливки, контура и тени, прозрачность заливки и контура, анимация цвета и альфы.'],
  blur: ['\\blur and \\be soften the whole fragment (approximation: fill and outline blur together). The last line sharpens over time.', '\\blur ve \\be tüm parçayı yumuşatır (yaklaşık: dolgu ve kenar birlikte bulanır). Son satır zamanla keskinleşir.', '\\blur и \\be размывают весь фрагмент (приблизительно: заливка и контур размываются вместе). Последняя строка со временем становится чёткой.'],
  bord: ['Outline widths, shadow distances and offsets. xbord != ybord uses the larger value (approximation).', 'Kenar kalınlıkları, gölge uzaklıkları ve kaymaları. xbord != ybord büyük değeri kullanır (yaklaşık).', 'Толщина контура, расстояние и смещение тени. При xbord != ybord берётся большее значение (приблизительно).'],
  clip: ['Only the left half of line 1 is visible, line 2 is revealed by an animated clip, line 3 uses the last \\clip.', '1. satırın yalnız sol yarısı görünür, 2. satır animasyonlu kırpmayla açılır, 3. satır son \\clip\'i kullanır.', 'Видна только левая половина первой строки, вторая открывается анимированной обрезкой, третья использует последний \\clip.'],
  iclip: ['A rectangular hole is cut out of the big text; the second hole grows over time.', 'Büyük metinden dikdörtgen bir delik açılır; ikinci delik zamanla büyür.', 'В большом тексте вырезано прямоугольное отверстие; второе отверстие со временем растёт.'],
  vclip: ['Text clipped to a diamond, a bar cut out by an inverse vector clip, and a scaled clip.', 'Metin elmas şekline kırpılır, ters vektör kırpmayla bir şerit çıkarılır, bir de ölçekli kırpma vardır.', 'Текст обрезан по ромбу, полоса вырезана обратной векторной обрезкой, плюс обрезка с масштабом.'],
  karaoke: ['\\k switches colour per syllable, \\kf sweeps left to right, \\ko reveals the outline, \\K sweeps like \\kf.', '\\k hece başına renk değiştirir, \\kf soldan sağa süpürür, \\ko kenarı açar, \\K de \\kf gibi süpürür.', '\\k переключает цвет по слогам, \\kf заливает слева направо, \\ko открывает контур, \\K работает как \\kf.'],
  drawing: ['Square, triangle, bezier circle, outlined step shape, \\p2 half-size shape, blurred bar, \\pbo-shifted bar and an inline drawing in text. Spline close is a straight close (approximation).', 'Kare, üçgen, bezier daire, kenarlı basamak, \\p2 ile yarı boy şekil, bulanık çubuk, \\pbo ile kaymış çubuk ve metin içinde çizim. Spline kapatma düz kapatmadır (yaklaşık).', 'Квадрат, треугольник, круг из безье, ступенчатая фигура с контуром, фигура \\p2 вдвое меньше, размытая полоса, полоса со сдвигом \\pbo и рисунок внутри текста.'],
  reset: ['\\r returns to the line style; \\rTop switches style; an unknown style falls back to the line style.', '\\r satır stiline döner; \\rTop stili değiştirir; bilinmeyen stil satır stiline düşer.', '\\r возвращает стиль строки; \\rTop переключает стиль; неизвестный стиль заменяется стилем строки.'],
  wrap: ['Four narrow boxes: q0/q3 balance the lines (approximation), q1 breaks greedily, q2 only breaks at \\N.', 'Dört dar kutu: q0/q3 satırları dengeler (yaklaşık), q1 doldurarak böler, q2 yalnız \\N\'de böler.', 'Четыре узких блока: q0/q3 балансируют строки (приблизительно), q1 переносит жадно, q2 переносит только по \\N.'],
  box: ['BorderStyle 3 draws an opaque box; \\bord sets its padding, \\3c its colour, \\shad a shadow box.', 'BorderStyle 3 opak bir kutu çizer; \\bord boşluğu, \\3c rengi, \\shad gölge kutusunu belirler.', 'BorderStyle 3 рисует сплошную плашку; \\bord задаёт отступ, \\3c цвет, \\shad теневую плашку.'],
  layers: ['Higher layers draw over lower ones; inside one layer the later line is on top.', 'Yüksek katmanlar alttakilerin üstüne çizilir; aynı katmanda sonraki satır üsttedir.', 'Верхние слои рисуются поверх нижних; внутри слоя позднейшая строка лежит выше.'],
  collision: ['Unpositioned lines stack upward from the bottom (downward at the top) and keep their place once shown.', 'Konumsuz satırlar alttan yukarı (üstte aşağı) dizilir ve görününce yerinden oynamaz.', 'Строки без позиции складываются снизу вверх (сверху вниз) и не сдвигаются после появления.'],
  comments: ['Only the visible lines show up; the Comment event and the inline {comment} text never render.', 'Yalnız görünür satırlar çıkar; Comment olayı ve satır içi {yorum} metni asla çizilmez.', 'Видны только обычные строки; событие Comment и встроенный {комментарий} никогда не рисуются.'],
  boundary: ['A line is visible from its start up to, but not including, its end, so at 1.00 s A is gone and B is there: never both, never neither. C starts at 2.02 s: at 24 fps it first shows on the frame at 2.042 s, not on 2.000 s. Z has no duration and never shows. Open the Lab, pick 24 / 30 / 60 fps and step frame by frame.', 'Bir satır başlangıcından bitişine kadar görünür, bitiş anı dahil değildir: 1,00 sn\'de A gider, B gelir; asla ikisi birden, asla ikisi de yok. C 2,02 sn\'de başlar: 24 fps\'de 2,000 sn karesinde değil, 2,042 sn karesinde görünür. Z\'nin süresi yok, hiç görünmez. Lab\'da 24 / 30 / 60 fps seçip kare kare ilerleyin.', 'Строка видна от начала до конца, но конец не включается: в 1,00 с A исчезает, B появляется; никогда обе и никогда ни одной. C начинается в 2,02 с: при 24 fps она впервые видна на кадре 2,042 с, а не 2,000 с. У Z нет длительности, она не показывается. Откройте Lab, выберите 24 / 30 / 60 fps и идите по кадрам.'],
  fontsEmbedded: ['The font is embedded in this script\'s [Fonts] section (see the text editor) and loads by itself: the first two lines are drawn as solid bars. The Fonts tab lists it as embedded; Arial comes from your device; the last name exists nowhere and is reported missing.', 'Font bu betiğin [Fonts] bölümüne gömülü (metin düzenleyiciye bakın) ve kendiliğinden yüklenir: ilk iki satır dolu çubuklarla çizilir. Yazı tipleri sekmesi onu gömülü olarak listeler; Arial cihazınızdan gelir; son ad hiçbir yerde yoktur ve eksik olarak bildirilir.', 'Шрифт встроен в раздел [Fonts] этого скрипта (см. редактор) и загружается сам: первые две строки рисуются сплошными столбиками. Вкладка шрифтов показывает его как встроенный; Arial берётся с вашего устройства; последнее имя нигде не существует и помечено как отсутствующее.'],
  fontsLibrary: ['Every line uses the generated test font, which has no Cyrillic glyphs. Fonts tab > Font library: download the test font, add it to the library, reload the page: the "font is missing" prompt is gone for good, and the Cyrillic line is flagged as lacking characters (boxes in the library preview).', 'Tüm satırlar üretilen test fontunu kullanır; fontta Kiril glifi yoktur. Yazı tipleri > Font kütüphanesi: test fontunu indirip kütüphaneye ekleyin, sayfayı yenileyin: "font eksik" uyarısı bir daha çıkmaz, Kiril satırı eksik karakterli diye işaretlenir (kütüphane önizlemesinde kutular).', 'Все строки используют сгенерированный тестовый шрифт, в нём нет кириллических глифов. Шрифты > Библиотека шрифтов: скачайте тестовый шрифт, добавьте в библиотеку, обновите страницу: предупреждение «шрифт отсутствует» больше не появится, а кириллическая строка помечена как содержащая отсутствующие символы (рамки в предпросмотре).'],
  fontsUser: ['Same lines, but the font is not embedded: the first two lines show as missing (fallback font). Open the Fonts tab and press "Load generated test font" (or drop your own .ttf): they switch to bars and the chip changes to user.', 'Aynı satırlar, ama font gömülü değil: ilk iki satır eksik görünür (yedek font). Yazı tipleri sekmesinde "Üretilen test fontunu yükle" düğmesine basın (ya da kendi .ttf dosyanızı bırakın): çubuklara döner, etiket kullanıcı olur.', 'Те же строки, но шрифт не встроен: первые две строки показаны как отсутствующие (запасной шрифт). Откройте вкладку шрифтов и нажмите «Загрузить тестовый шрифт» (или перетащите свой .ttf): строки станут столбиками, метка сменится на «свой».'],
  stress: ['90 simultaneous lines with move, rotation, blur and colour. Watch the measured render FPS and the active line count.', 'Aynı anda 90 satır: hareket, dönüş, bulanıklık ve renk. Ölçülen çizim FPS ve etkin satır sayısını izleyin.', '90 одновременных строк с движением, вращением, размытием и цветом. Следите за измеренным FPS и числом активных строк.'],
  unsupported: ['Not implemented: \\fe is parsed and ignored, Effect Banner / Scroll are ignored, \\kf on a drawing switches colour only at the end.', 'Uygulanmadı: \\fe ayrıştırılır ama yok sayılır, Effect Banner / Scroll yok sayılır, çizimde \\kf rengi yalnız sonda değiştirir.', 'Не реализовано: \\fe разбирается, но игнорируется, Effect Banner / Scroll игнорируются, \\kf на рисунке меняет цвет только в конце.'],
};

const IDX: Record<Lang, number> = { en: 0, tr: 1, ru: 2 };
export const hintFor = (id: string, lang: Lang): string => H[id]?.[IDX[lang]] ?? '';
